version: '2'
services: 
  sensors:
        build: ./sensors
        privileged: true
        restart: always
        labels:
                io.balena.features.dbus: '1'
                io.balena.features.kernel-modules: '1'
        ports:
                - "80"