FROM balenalib/raspberrypi3-debian:stretch-20190612

RUN apt-get update && \
    apt-get install -yq \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
&& apt-get clean && rm -rf /var/lib/apt/lists/*


RUN pip3 install --upgrade pip 
RUN pip3 install adafruit-circuitpython-bme680 requests aiohttp --index-url https://www.piwheels.org/simple

WORKDIR /usr/src/app

COPY ./app/ /usr/src/app/

CMD ["python3", "/usr/src/app/main.py"]